# Generated by Django 4.2.30 on 2026-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(blank=True, help_text='Small label above title', max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=350)),
                ('image', models.ImageField(blank=True, help_text='Background image (recommended 1920×800px)', null=True, upload_to='hero/')),
                ('gradient', models.CharField(default='linear-gradient(135deg, #1B365D 0%, #2E6EB3 50%, #F39200 100%)', help_text='CSS gradient overlay when no image, or over image', max_length=300)),
                ('primary_btn_text', models.CharField(default='View Products', max_length=50)),
                ('primary_btn_url', models.CharField(default='/products/', max_length=200)),
                ('secondary_btn_text', models.CharField(blank=True, max_length=50)),
                ('secondary_btn_url', models.CharField(blank=True, max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'verbose_name_plural': 'Hero Slides',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
