# Generated by Django 4.2.30 on 2026-07-16 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_heroslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Milestone',
                'verbose_name_plural': 'About Milestones',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='About East Eagle Energy', max_length=100)),
                ('hero_title', models.CharField(default='Energy That Never Grows Weary', max_length=200)),
                ('hero_subtitle', models.CharField(default='Global solar, storage, and power solutions — built for reliability since 2022.', max_length=350)),
                ('aims_intro', models.TextField(default='East Eagle Energy was founded with a clear purpose: to make dependable, clean energy accessible to homes, businesses, and industries worldwide.')),
                ('mission_eyebrow', models.CharField(default='Our Mission', max_length=100)),
                ('mission_title', models.CharField(default='Resilient Energy for Every Project', max_length=200)),
                ('mission_text', models.TextField(default='To supply energy solutions — inverters, battery storage, solar panels, and EV charging systems — that remain resilient and dependable over time. We believe power should never grow weary, whether for a family home, a commercial building, or an industrial facility.')),
                ('mission_quote', models.CharField(default='Energy That Never Grows Weary.', max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Page',
            },
        ),
        migrations.CreateModel(
            name='AboutValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='fa-globe', help_text='Font Awesome class, e.g. fa-globe', max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'About Value',
                'verbose_name_plural': 'About Values',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
