# Generated by Django 4.2.30 on 2026-07-09 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSidebarSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('c_and_i_bess', 'C & I BESS'), ('ess_solution', 'ESS Solution')], help_text='Which product category this sidebar is for', max_length=20, unique=True)),
                ('title', models.CharField(default='Product Categories', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description text shown at top of sidebar')),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product Sidebar Section',
                'verbose_name_plural': 'Product Sidebar Sections',
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='voltage_type',
            field=models.CharField(choices=[('low_voltage', 'Low Voltage'), ('high_voltage', 'High Voltage'), ('not_applicable', 'N/A')], default='not_applicable', help_text='For Residential products: Low Voltage or High Voltage', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('c_and_i_bess', 'C & I BESS'), ('ess_solution', 'ESS Solution')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductSidebarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sidebar/')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('link_url', models.CharField(blank=True, help_text='Optional link URL', max_length=200)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('sidebar_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productsidebarsection')),
            ],
            options={
                'verbose_name': 'Sidebar Image',
                'verbose_name_plural': 'Sidebar Images',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
