# Generated by Django 4.2.30 on 2026-07-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_migrate_categories_and_voltage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ess_sub_type',
            field=models.CharField(choices=[('low_voltage_ess', 'Low Voltage ESS'), ('high_voltage_ess', 'High Voltage ESS'), ('stacked_ess', 'Stacked ESS'), ('all_in_one_ess', 'All-in-One ESS'), ('storage_charging', 'Storage & Charging'), ('not_applicable', 'N/A')], default='not_applicable', help_text='ESS sub-category for sidebar navigation (C&I BESS, ESS Solution)', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('energy_storage', 'Energy Storage System'), ('inverter', 'Inverter')], default='energy_storage', help_text='Energy Storage System or Inverter', max_length=20),
        ),
    ]
