# Generated by Django 4.2.30 on 2026-07-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_classify_product_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('c_and_i_bess', 'C & I Energy Storage Systems'), ('ess_solution', 'ESS Solution')], max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='ess_sub_type',
            field=models.CharField(choices=[('low_voltage_ess', 'Low Voltage ESS'), ('high_voltage_ess', 'High Voltage ESS'), ('stacked_ess', 'Stacked ESS'), ('all_in_one_ess', 'All-in-One ESS'), ('storage_charging', 'Storage & Charging'), ('smart_energy_management', 'Smart Energy Management System'), ('cloud_monitoring', 'Cloud Monitoring'), ('not_applicable', 'N/A')], default='not_applicable', help_text='ESS sub-category for sidebar navigation (C&I BESS, ESS Solution)', max_length=30),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('energy_storage', 'Energy Storage System'), ('inverter', 'Inverter'), ('solar_panel', 'Solar Panel'), ('ev_charger', 'EV Charger')], default='energy_storage', help_text='Energy Storage System or Inverter', max_length=30),
        ),
        migrations.AlterField(
            model_name='productsidebarsection',
            name='category',
            field=models.CharField(choices=[('residential', 'Residential'), ('c_and_i_bess', 'C & I Energy Storage Systems'), ('ess_solution', 'ESS Solution')], help_text='Which product category this sidebar is for', max_length=20, unique=True),
        ),
    ]
