# Generated by Django 4.2.30 on 2026-07-11 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_category_alter_product_ess_sub_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Leave blank to use the product name', max_length=150)),
                ('subtitle', models.CharField(blank=True, help_text='Short promo line under the title', max_length=250)),
                ('badge', models.CharField(choices=[('best_seller', 'Best Seller'), ('featured', 'Featured'), ('hot_deal', 'Hot Deal'), ('new', 'New Arrival'), ('popular', 'Popular'), ('promo', 'Promo')], default='best_seller', max_length=20)),
                ('image', models.ImageField(blank=True, help_text='Promo image (uses product image if empty)', null=True, upload_to='recommended/')),
                ('link_url', models.CharField(blank=True, help_text='Optional custom link. Blank = product page URL', max_length=300)),
                ('button_text', models.CharField(default='View Product', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, help_text='Optional: link to a catalog product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='products.product')),
            ],
            options={
                'verbose_name': 'Recommended Product',
                'verbose_name_plural': 'Recommended Products',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
